/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugRunIdIssueIdRouteImport } from './routes/debug.$runId.$issueId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRunIdIssueIdRoute = DebugRunIdIssueIdRouteImport.update({
  id: '/debug/$runId/$issueId',
  path: '/debug/$runId/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug/$runId/$issueId': typeof DebugRunIdIssueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug/$runId/$issueId': typeof DebugRunIdIssueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug/$runId/$issueId': typeof DebugRunIdIssueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/debug/$runId/$issueId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/debug/$runId/$issueId'
  id: '__root__' | '/' | '/debug/$runId/$issueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRunIdIssueIdRoute: typeof DebugRunIdIssueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/$runId/$issueId': {
      id: '/debug/$runId/$issueId'
      path: '/debug/$runId/$issueId'
      fullPath: '/debug/$runId/$issueId'
      preLoaderRoute: typeof DebugRunIdIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRunIdIssueIdRoute: DebugRunIdIssueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
