/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ExplainDemoRouteImport } from './routes/explain-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplainFlowRouteImport } from './routes/explain.$flow'
import { Route as FormsRunIdIssueIdRouteImport } from './routes/forms.$runId.$issueId'

const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainDemoRoute = ExplainDemoRouteImport.update({
  id: '/explain-demo',
  path: '/explain-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainFlowRoute = ExplainFlowRouteImport.update({
  id: '/explain/$flow',
  path: '/explain/$flow',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRunIdIssueIdRoute = FormsRunIdIssueIdRouteImport.update({
  id: '/forms/$runId/$issueId',
  path: '/forms/$runId/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explain-demo': typeof ExplainDemoRoute
  '/inbox': typeof InboxRoute
  '/explain/$flow': typeof ExplainFlowRoute
  '/forms/$runId/$issueId': typeof FormsRunIdIssueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explain-demo': typeof ExplainDemoRoute
  '/inbox': typeof InboxRoute
  '/explain/$flow': typeof ExplainFlowRoute
  '/forms/$runId/$issueId': typeof FormsRunIdIssueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explain-demo': typeof ExplainDemoRoute
  '/inbox': typeof InboxRoute
  '/explain/$flow': typeof ExplainFlowRoute
  '/forms/$runId/$issueId': typeof FormsRunIdIssueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explain-demo'
    | '/inbox'
    | '/explain/$flow'
    | '/forms/$runId/$issueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explain-demo'
    | '/inbox'
    | '/explain/$flow'
    | '/forms/$runId/$issueId'
  id:
    | '__root__'
    | '/'
    | '/explain-demo'
    | '/inbox'
    | '/explain/$flow'
    | '/forms/$runId/$issueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplainDemoRoute: typeof ExplainDemoRoute
  InboxRoute: typeof InboxRoute
  ExplainFlowRoute: typeof ExplainFlowRoute
  FormsRunIdIssueIdRoute: typeof FormsRunIdIssueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain-demo': {
      id: '/explain-demo'
      path: '/explain-demo'
      fullPath: '/explain-demo'
      preLoaderRoute: typeof ExplainDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain/$flow': {
      id: '/explain/$flow'
      path: '/explain/$flow'
      fullPath: '/explain/$flow'
      preLoaderRoute: typeof ExplainFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$runId/$issueId': {
      id: '/forms/$runId/$issueId'
      path: '/forms/$runId/$issueId'
      fullPath: '/forms/$runId/$issueId'
      preLoaderRoute: typeof FormsRunIdIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplainDemoRoute: ExplainDemoRoute,
  InboxRoute: InboxRoute,
  ExplainFlowRoute: ExplainFlowRoute,
  FormsRunIdIssueIdRoute: FormsRunIdIssueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
